### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'EnumMeta' and 'EnumMeta'

### ISSUE THREAD

**Issue by dbrennand** [leonhard-s/ps2-rich-presence#9]
Hi,

I just tried using the app but I get the following exception and traceback:

```
WARNING: CPU random generator seem to be failing, disabling hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\GitHub\ps2-rich-presence\ps2rpc\__main__.py", line 10, in <module>
    from ._app import Application
  File "C:\Users\user\GitHub\ps2-rich-presence\ps2rpc\_app.py", line 8, in <module>
    from ._rpc import RPCHandler
  File "C:\Users\user\GitHub\ps2-rich-presence\ps2rpc\_rpc.py", line 15, in <module>
    from .presence import PresencePayload
  File "C:\Users\user\GitHub\ps2-rich-presence\ps2rpc\presence\__init__.py", line 8, in <module>
    from ._factory import PresenceFactory
  File "C:\Users\user\GitHub\ps2-rich-presence\ps2rpc\presence\_factory.py", line 8, in <module>
    from ..game import GameState, Ps2Class
  File "C:\Users\user\GitHub\ps2-rich-presence\ps2rpc\game\__init__.py", line 10, in <module>
    from ._gamestate import GameState, GameStateFactory
  File "C:\Users\user\GitHub\ps2-rich-presence\ps2rpc\game\_gamestate.py", line 14, in <module>
    class GameState:
  File "C:\Users\user\GitHub\ps2-rich-presence\ps2rpc\game\_gamestate.py", line 21, in GameState
    profile: Ps2Class | Ps2Vehicle
TypeError: unsupported operand type(s) for |: 'EnumMeta' and 'EnumMeta'
```

Installation/Usage steps:

1. `git clone git@github.com:leonhard-s/ps2-rich-presence.git; cd ps2-rich-presence`
2. `python -m venv .`
3. `.\Scripts\Activate.ps1`
4. `pip install -r .\requirements.txt`
5. `python -m ps2rpc`

**Comment by dbrennand** [comment]
Ah, I think it may be something to do with my Python version.

**Comment by dbrennand** [comment]
Yep 😄 All good now. Apologies! 👍🏻
